networks:
  internal:

services:
  ui:
    container_name: test
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - internal
    ports:
      - 3000:3000

    environment:
      API_URL: 'http://api:8000'
